config/routes.rb
Rails.application.routes.draw do
  
  get 'charge/create'

  root :to => 'home#index'
  get 'home/create'
  get 'home/login_link', as: 'login_link'
  get 'home/destroy_plan', as: 'destroy_plan'
  mount ShopifyApp::Engine, at: '/'

  # See how all your routes lay out with "rake routes".

  # You can have the root of your site routed with "root"
  # root 'welcome#index'

  # Example of regular route:
  #   get 'pRails.application.routes.draw d

  #   get 'products/:id/purchase' => 'catalog#purchase', as: :purchase

  # Example resource route (maps HTTP verbs to controller actions automatically):
  #   resources :products

  # Example resource route with options:
  #   resources :products do
  #     member do
  #       get 'short'
  #       post 'toggle'
  #     end
  #
  #     collection do
  #       get 'sold'
  #     end
  #   end

  # Example resource route with sub-resources:
  #   resources :products do
  #     resources :comments, :sales
  #     resource :seller
  #   end

  # Example resource route with more complex sub-resources:
  #   resources :products do
  #     resources :comments
  #     resources :sales do
  #       get 'recent', on: :collection
  #     end
  #   end

  # Example resource route with concerns:
  #   concern :toggleable do
  #     post 'toggle'
  #   end
  #   resources :posts, concerns: :toggleable
  #   resources :photos, concerns: :toggleable

  # Example resource route within a namespace:
  #   namespace :admin do
  #     # Directs /admin/products/* to Admin::ProductsController
  #     # (app/controllers/admin/products_controller.rb)
  #     resources :products
  #   end
end

app/models/market_goo_id.rb
class MarketGooId < ActiveRecord::Base
	has_one :shop
end

app/models/plan.rb
class Plan < ActiveRecord::Base
	has_many :shops
end

app/models/shop.rb
class Shop < ActiveRecord::Base
  include ShopifyApp::Shop
  include ShopifyApp::SessionStorage
  after_create :init_webhooks
  has_one :market_goo_id
  has_one :plan

  def self.find_by_shop_domain(shop_domain)
    self.where(shopify_domain: shop_domain).first
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  require 'rest-client'
  require 'json'
  include ShopifyApp::LoginProtection
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ShopifyApp::AuthenticatedController
  def index
    @products = ShopifyAPI::Product.find(:all, params: { limit: 10 })
    @shop = Shop.find_by_shopify_domain(ShopifyAPI::Shop.current.domain)
    # if @shop.market_goo_id.nil?
    #   # create
    # end
    plan
  end

  # def create 
  #   @shop = ShopifyAPI::Shop.current   

  #   params = {domain: @shop.domain, email: @shop.email }

  #   #we need to post to this address, that will give us a response which is the MARKETGOO ID
  #   response = RestClient.post 'https://webviking.stage.mktgoo.net/api/accounts', params
   
  #   # You will need to create this field in the database on your Shop model, this will then store the MarketGoo Id which we will need shortly

  #   plan
 
  # end

  # def create_shop
  #   shop = Shop.new
  #   shop.id = ShopifyAPI::Shop.current.id
  #   shop.shopify_domain = ShopifyAPI::Shop.current.domain
  #   shop.market_goo_id = @market_goo_id.id
  #   shop.save

  #   binding.pry

  #   plan
  # end

  def plan
    @plan = Plan.new 
    @plan.name = "Free"  
    @plan.price = 0
    @plan.description = "1 website, Limited Dashboard Access, Summarized report, One time report, Highlights only"
    @plan.shop_id = ShopifyAPI::Shop.current.id
    @plan.save

    save_shop_plan_id
  end

  def upgrade_plan
    @new_plan = Plan.new
    @new_plan.name = "Premiun"
    @new_plan.price = 19.95
    @new_plan.description = "1 website, Full report, Monthly reports, Auto submit to Social Media, Daily scan of competitor websites, Customisable reports, Marketing Stats and Metrics, Website Results Tool, Personalised Marketing Plan, Step by step guide to improve your website, Steps explained in detail, Checklist of to do and completed issues, Cancel at any time"
    @new_plan.shop_id = ShopifyAPI::Shop.current.id
    @new_plan.save

    save_new_shop_plan_id
  end

  def destroy_plan
    shop_id = ShopifyAPI::Shop.current.id
    find_plan = Plan.find_by(shop_id: shop_id)
    find_plan.destroy

    upgrade_plan
  end

  def save_shop_plan_id
    @shop = Shop.find_by_shopify_domain(ShopifyAPI::Shop.current.domain)
    @shop.plan_id = @plan.id
    @shop.save
  end

  def save_new_shop_plan_id
    @shop = Shop.find_by_shopify_domain(ShopifyAPI::Shop.current.domain)
    @shop.plan_id = @new_plan.id
    @shop.save

    get_market_goo_id
  end
    

  def get_market_goo_id
    @shop = ShopifyAPI::Shop.current   

    @market_goo_id = MarketGooId.new();
    @market_goo_id.shop_id = @shop.id;
    @market_goo_id.shop_domain = @shop.domain;
    
    product = 'evolution'

    params = {product: product, domain: @shop.domain, name: @shop.shop_owner, email: @shop.email, promo: @shop.domain}

    #we need to post to this address, that will give us a response which is the MARKETGOO ID
    response = RestClient.post 'https://webviking.stage.mktgoo.net/api/accounts', params, :'X-Auth-Token' => "1bb6343e8153b342f346b9559938cdb0d927a8ed"
   
    # You will need to create this field in the database on your Shop model, this will then store the MarketGoo Id which we will need shortly.
    @market_goo_id.app_id = response.body

    #Save the shiz
    @market_goo_id.save
    create_subscription
  end

  def login_link
   @shop = ShopifyAPI::Shop.current
   @market_goo_id = MarketGooId.find_by_shop_domain(@shop.domain)
   RestClient::Request.execute(method: :get, url: "https://webviking.stage.mktgoo.net/api/login/#{@market_goo_id.app_id}", :headers => {"X-Auth-Token"=> "1bb6343e8153b342f346b9559938cdb0d927a8ed"}) do |response, request, result, &block|
     if [301, 302, 307].include? response.code
       redirected_url = response.headers[:location]
       redirect_to redirected_url
     else
       response.return!(request, result, &block)
     end
  end
 end

  def create_subscription
       # checks to see if there is already an RecurringApplicationCharge created and activated
    unless ShopifyAPI::RecurringApplicationCharge.current
      recurring_application_charge = ShopifyAPI::RecurringApplicationCharge.new(
                name: "Premiun",
                price: 19.99,
                return_url: ShopifyAPI::Shop.current.domain+"activatecharge",
                trial_days: 0)
        # if the new RecurringApplicationCharge saves,redirect the user to the confirmation URL,
        # so they can accept or decline the charge
      if recurring_application_charge.save
          @tokens[:confirmation_url] = recurring_application_charge.confirmation_url
          redirect recurring_application_charge.confirmation_url
      end
    end
 end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/charge_helper.rb
module ChargeHelper
end

app/helpers/plan_helper.rb
module PlanHelper
end

app/views/charge/create.html.erb
<h1>Charge#create</h1>
<p>Find me in app/views/charge/create.html.erb</p>

app/views/home/index.html.erb
<% content_for :javascript do %>
  <script type="text/javascript">
    ShopifyApp.ready(function(){
      ShopifyApp.Bar.initialize({
        title: "Home",
        icon: "<%= asset_path('favicon.ico') %>"
      });
    });
  </script>
<% end %>

<%= link_to 'Upgrade Plan', destroy_plan_path, class: 'btn btn--fill btn--small btn--color', target: "_blank" %>

<%= link_to 'Manage SEO', login_link_path, class: 'btn btn--fill btn--small btn--color', target: "_blank" %>

app/views/layouts/_flash_messages.html.erb
<% content_for :javascript do %>
<script type="text/javascript">
  var eventName = typeof(Turbolinks) !== 'undefined' ? 'page:change' : 'DOMContentLoaded';

  document.addEventListener(eventName, function() {
    <% if flash[:notice] %>
      ShopifyApp.flashNotice("<%= j flash[:notice].html_safe %>");
    <% end %>

    <% if flash[:error] %>
      ShopifyApp.flashError("<%= j flash[:error].html_safe %>");
    <% end %>
  });
</script>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>WebViking2</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/layouts/embedded_app.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <title>Shopify Embedded Example App</title>
    <%= stylesheet_link_tag 'application' %>
    <%= csrf_meta_tags %>
  </head>

  <body>
    <div class="app-wrapper">
      <div class="app-content">
        <main role="main">
          <%= yield %>
        </main>
      </div>
    </div>

    <%= render 'layouts/flash_messages' %>

    <script src="https://cdn.shopify.com/s/assets/external/app.js?<%= Time.now.strftime('%Y%m%d%H') %>"></script>

    <script type="text/javascript">
      ShopifyApp.init({
        apiKey: "<%= ShopifyApp.configuration.api_key %>",
        shopOrigin: "<%= "https://#{ @shop_session.url }" if @shop_session %>",
        debug: <%= Rails.env.development? ? 'true' : 'false' %>,
        forceRedirect: true
      });
    </script>

    <%= javascript_include_tag 'application', "data-turbolinks-track" => true %>

    <% if content_for?(:javascript) %>
      <div id="ContentForJavascript" data-turbolinks-temporary>
        <%= yield :javascript %>
      </div>
    <% end %>
  </body>
</html>

app/views/plan/create.html.erb
<h1>Plan#create</h1>
<p>Find me in app/views/plan/create.html.erb</p>

app/views/plan/index.html.erb
<h1>Plan#index</h1>
<p>Find me in app/views/plan/index.html.erb</p>